In [ ]:
### The matrix will be 4x4 since we have 4 features in the IRIS dataset, and also 4 eigenvalues.


In [13]:
import numpy as np
import pandas as pd

data = pd.read_csv('iris.data', delimiter=',', header=None, usecols=lambda x: x != 4)
data = data.apply(pd.to_numeric) # ensure numeric
cov_matrix = np.cov(data, rowvar=False)

print(cov_matrix)

[[ 0.68569351 -0.03926846  1.27368233  0.5169038 ]
 [-0.03926846  0.18800403 -0.32171275 -0.11798121]
 [ 1.27368233 -0.32171275  3.11317942  1.29638747]
 [ 0.5169038  -0.11798121  1.29638747  0.58241432]]


In [41]:
import altair as alt


my_columns = ["Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.With"]
cov_matrix = pd.DataFrame(data.cov(), columns=my_columns, index=my_columns)
data.columns = my_columns # add column names

# prepare data in pairs for easier handling
pairwise_data = []
for feature_x in my_columns:
    for feature_y in my_columns:
        pairwise_data.append(
            pd.DataFrame({
                "Feature_X": feature_x,
                "Feature_Y": feature_y,
                "Value_X": data[feature_x],
                "Value_Y": data[feature_y]
            })
        )
pairwise_data = pd.concat(pairwise_data, ignore_index=True)


scatter = alt.Chart(pairwise_data).mark_point(size=30, opacity=0.7).encode(
    x=alt.X('Value_X:Q', title=None, scale=alt.Scale(zero=False)),
    y=alt.Y('Value_Y:Q', title=None, scale=alt.Scale(zero=False)),
    color=alt.Color('Feature_X:N', legend=None),
).properties(
    width = 100,
    height = 100
)
faceted_chart = scatter.facet(
    row=alt.Row('Feature_Y:N', title=None),
    column=alt.Column('Feature_X:N', title=None),
).resolve_scale(x='independent', y='independent')

faceted_chart

         Feature_X     Feature_Y  Value_X  Value_Y
0     Sepal.Length  Sepal.Length      5.1      5.1
1     Sepal.Length  Sepal.Length      4.9      4.9
2     Sepal.Length  Sepal.Length      4.7      4.7
3     Sepal.Length  Sepal.Length      4.6      4.6
4     Sepal.Length  Sepal.Length      5.0      5.0
...            ...           ...      ...      ...
2395    Petal.With    Petal.With      2.3      2.3
2396    Petal.With    Petal.With      1.9      1.9
2397    Petal.With    Petal.With      2.0      2.0
2398    Petal.With    Petal.With      2.3      2.3
2399    Petal.With    Petal.With      1.8      1.8

[2400 rows x 4 columns]


alt.FacetChart(...)